// <auto-generated />
namespace SimpleListContext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addinglogin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addinglogin));
        
        string IMigrationMetadata.Id
        {
            get { return "201310251319469_addinglogin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
