// <auto-generated />
namespace SimpleListContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class add_dates_to_userlist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_dates_to_userlist));
        
        string IMigrationMetadata.Id
        {
            get { return "201311011412146_add_dates_to_userlist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
