// <auto-generated />
namespace SimpleListContext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class M0001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M0001));
        
        string IMigrationMetadata.Id
        {
            get { return "201310150256209_M0001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
