// <auto-generated />
namespace SimpleListContext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RelinkedUserToLogin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelinkedUserToLogin));
        
        string IMigrationMetadata.Id
        {
            get { return "201310251547453_RelinkedUserToLogin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
