// <auto-generated />
namespace SimpleListContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class add_list_status : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_list_status));
        
        string IMigrationMetadata.Id
        {
            get { return "201311021454528_add_list_status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
