// <auto-generated />
namespace SimpleListContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class AddingItemParts01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingItemParts01));
        
        string IMigrationMetadata.Id
        {
            get { return "201401280221563_AddingItemParts01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
